# Generated by Django 3.1.2 on 2021-07-11 11:59

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(blank=True, max_length=200, null=True)),
                ('news_image', models.FileField(blank=True, null=True, upload_to='news_images/')),
                ('news_description', ckeditor.fields.RichTextField(blank=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(blank=True, max_length=100, null=True)),
                ('page_image', models.FileField(blank=True, null=True, upload_to='page_images/')),
                ('page_description', ckeditor.fields.RichTextField(blank=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('page_online', models.BooleanField(default=True, verbose_name='Online Click Yes ')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slider_description', models.CharField(max_length=100)),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='slider_images/')),
                ('order', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=100)),
                ('slider_online', models.BooleanField(default=True)),
            ],
        ),
    ]
